-- 코드를 입력하세요
SELECT A.CART_ID

FROM
(SELECT CART_ID, COUNT(CART_ID) AS CNT1
FROM CART_PRODUCTS
WHERE NAME = 'YOGURT'
GROUP BY CART_ID) AS A
INNER JOIN
(SELECT CART_ID, COUNT(CART_ID) AS CNT2
FROM CART_PRODUCTS
WHERE NAME = 'MILK'
GROUP BY CART_ID) AS B
ON A.CART_ID = B.CART_ID

WHERE A.CNT1>0 AND B.CNT2>0