-- 코드를 작성해주세요
WITH RECURSIVE EH AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, H.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN EH H ON E.PARENT_ID=H.ID
    WHERE H.GENERATION<3
)

SELECT ID
FROM EH
WHERE GENERATION=3
ORDER BY ID ASC