-- 코드를 작성해주세요
SELECT D.ID, CASE WHEN D.COLONY_RANK = 1 THEN 'CRITICAL'
                  WHEN D.COLONY_RANK = 2 THEN 'HIGH'
                  WHEN D.COLONY_RANK = 3 THEN 'MEDIUM'
                  ELSE 'LOW'
             END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) COLONY_RANK
      FROM ECOLI_DATA
     ) AS D
ORDER BY D.ID ASC
