SELECT
    x.HISTORY_ID,
    ROUND(
        CASE
            WHEN x.DURATION >= 90 THEN x.DAILY_FEE * x.DURATION * (100 - REPLACE(p.DISCOUNT_RATE, '%', '')) / 100
            WHEN x.DURATION >= 30 THEN x.DAILY_FEE * x.DURATION * (100 - REPLACE(p.DISCOUNT_RATE, '%', '')) / 100
            WHEN x.DURATION >= 7 THEN x.DAILY_FEE * x.DURATION * (100 - REPLACE(p.DISCOUNT_RATE, '%', '')) / 100
            ELSE x.DAILY_FEE * x.DURATION
        END,
        0
    ) AS FEE
FROM (
    SELECT
        h.HISTORY_ID,
        c.CAR_TYPE,
        c.DAILY_FEE,
        DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c
        ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
) x
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON x.CAR_TYPE = p.CAR_TYPE
   AND (
        (x.DURATION >= 90 AND p.DURATION_TYPE = '90일 이상')
        OR (x.DURATION >= 30 AND x.DURATION < 90 AND p.DURATION_TYPE = '30일 이상')
        OR (x.DURATION >= 7 AND x.DURATION < 30 AND p.DURATION_TYPE = '7일 이상')
   )
ORDER BY FEE DESC, HISTORY_ID DESC;