-- 코드를 입력하세요
WITH TEMP AS (
    SELECT R.MEMBER_ID, COUNT(R.MEMBER_ID) AS CNT
    FROM MEMBER_PROFILE P JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
    GROUP BY R.MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
)


SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE PR JOIN REST_REVIEW RE ON PR.MEMBER_ID = RE.MEMBER_ID
WHERE RE.MEMBER_ID = (SELECT MEMBER_ID FROM TEMP)
ORDER BY REVIEW_DATE, REVIEW_TEXT